### ISSUE TITLE
Luther crashes the game

### ISSUE THREAD

**Issue by cascer1** [Dubpubber/The-Creative-Grant-Mod#1]
Whenever I spawn Luther, the game crashes. I don't get any error messages.

Playing v1.0 of PA

**Comment by Dubpubber** [comment]
Thanks, I'll update to the mod to the latest version!

**Comment by Dubpubber** [comment]
Updated to newest version of PA, let me know if it still crashes.

**Comment by Dubpubber** [comment]
Closed and marked as resolved.
